/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("application")
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("software.amazon.awscdk:aws-cdk-lib:2.114.1")
    api("software.constructs:constructs:[10.0.0,11.0.0)")
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.1")
}

group = "org.piotrhosa.tui"
version = "0.1"
description = "cdk"
java.sourceCompatibility = JavaVersion.VERSION_11

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

application {
    mainClass.set("org.piotrhosa.tui.CdkApp")
}
